trigger:
- main  # Replace with your target branch

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: self
    connections:
      - serviceConnection: 'cluster1'  # Replace with the name of your service connection
        source: p4s-deploy  # Replace with the name of your GitHub repository

jobs:
- job: deploy
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: UseTerraform@2
    inputs:
      terraformVersion: 'latest'

  - script: |
      terraform init
      terraform plan -out=tfplan
    displayName: 'Initialize and Plan Terraform'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: .terraform
      artifactName: 'terraform-output'
