# azure-pipelines.yml

trigger:
- main  # Adjust the branch name as needed

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      installationScript: 'install'

  - script: |
      # Build .NET application
      cd MyDotNetApp  # Replace with the actual path to your .NET project
      dotnet build
    displayName: 'Build .NET Application'

  - script: |
      # Authenticate with Azure Container Registry (ACR)
      az acr login --name p4s101231 --resource-group p4s-ACR-rg

      # Build and push Docker image to ACR
      docker build -t p4s101231.azurecr.io/p4s-k8s-image:$(Build.BuildId) -f Dockerfile .
      docker push p4s101231.azurecr.io/p4s-k8s-image:$(Build.BuildId)

      # Set Azure AD application details as environment variables
      echo "export AZURE_CLIENT_ID=62ba6d2f-4192-4cf5-a00d-42328f7d7dfd" >> $(profile)
      echo "export AZURE_TENANT_ID=104e77d4-81e7-4c16-ab44-935220bed6dd" >> $(profile)
      echo "export AZURE_CLIENT_SECRET=nJP8Q~_EqLNHRP2WxOe.b1HjVrKytOXVprvW1ca9" >> $(profile)
    displayName: 'Build and Push Docker Image'
