name: Deploy Kubernetes Cluster

trigger:
  branches:
    exclude:
      - '*'  # Replace with your branch exclusion pattern

pr:
  - '*'

jobs:
  - job: deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
        sudo apt-get update && sudo apt-get install terraform
      displayName: 'Install Terraform'

    - script: terraform --version
      displayName: 'Terraform Version'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'cluster1'  # Use your service connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show'

    - script: |
        # Clone your GitHub repository
        git clone https://github.com/personal4slim/p4s-deploy.git
        cd p4s-deploy/smalldeploy
        
        # Create the Terraform directory path
        mkdir -p .terraform
        
        # Initialize Terraform
        terraform init
      displayName: 'Initialize Terraform'

    - script: |
        # Use the Terraform configuration directory
        cd p4s-deploy/smalldeploy
        
        # Plan Terraform
        terraform plan -out=tfplan -destroy
      displayName: 'Plan Terraform (Destroy)'

    - script: |
        # Use the Terraform configuration directory
        cd p4s-deploy/smalldeploy
        
        # Apply Terraform
        terraform apply -auto-approve tfplan
      displayName: 'Apply Terraform'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/p4s-deploy/smalldeploy/.terraform'
        artifact: 'terraform-output'
