trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: deploy
  timeoutInMinutes: 20 # Increased timeout to 20 minutes

  steps:
  - checkout: self

  - script: |
      # Create the Kubernetes manifest directory if it doesn't exist
      mkdir -p $(Build.ArtifactStagingDirectory)/kubernetes-manifest

      # Generate the Kubernetes manifest files with a unique identifier based on the build number
      cat <<EOF > $(Build.ArtifactStagingDirectory)/kubernetes-manifest/dev-manifest-$(Build.BuildNumber).yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
        namespace: dev
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
          metadata:
            labels:
              app: my-app
          spec:
            containers:
              - name: my-app
                image: p4s101231.azurecr.io/p4s-k8s-image:latest
                ports:
                  - containerPort: 8080
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                  - name: CONNECTION_STRING
                    value: "your_database_connection_string"
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: my-app-service
        namespace: dev
      spec:
        selector:
          app: my-app
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
        type: LoadBalancer
      EOF

      # ... (Repeat similar sections for test and prod)

    displayName: 'Create Kubernetes Manifest'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/kubernetes-manifest'
      artifact: 'kubernetes-manifest'

# Deployment stages for dev, test, and prod
- stage: DeployToDev
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Delete previous Kubernetes manifest files in the target namespace
        kubectl delete -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/dev-manifest-$(Build.BuildNumber).yaml --ignore-not-found=true

        # Apply the new Kubernetes manifest
        kubectl apply -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/dev-manifest-$(Build.BuildNumber).yaml
      displayName: 'Deploy to Dev'

- stage: DeployToTest
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Delete previous Kubernetes manifest files in the target namespace
        kubectl delete -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/test-manifest-$(Build.BuildNumber).yaml --ignore-not-found=true

        # Apply the new Kubernetes manifest
        kubectl apply -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/test-manifest-$(Build.BuildNumber).yaml
      displayName: 'Deploy to Test'

- stage: DeployToProd
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Delete previous Kubernetes manifest files in the target namespace
        kubectl delete -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/prod-manifest-$(Build.BuildNumber).yaml --ignore-not-found=true

        # Apply the new Kubernetes manifest
        kubectl apply -f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/prod-manifest-$(Build.BuildNumber).yaml
      displayName: 'Deploy to Prod'
