trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  servicePrincipalId: '62ba6d2f-4192-4cf5-a00d-42328f7d7dfd'
  servicePrincipalKey: 'nJP8Q~_EqLNHRP2WxOe.b1HjVrKytOXVprvW1ca9'
  tenantId: '104e77d4-81e7-4c16-ab44-935220bed6dd'
  subscriptionId: '606e824b-aaf7-4b4e-9057-b459f6a4436d'
  acrName: 'p4s101231'  # Replace with your ACR name
  resourceGroupName: 'YOUR_RESOURCE_GROUP_NAME'  # Replace with your resource group name
  imagePath: 'YOUR_IMAGE_PATH'  # Replace with your image path

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    az acr login --name $(acrName)
    az acr helm push $(imagePath):$(Build.BuildId) $(acrName)
  displayName: 'Login to Azure and Push Helm Chart to ACR'

- script: |
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    az acr helm repo list -n $(acrName)
    az acr helm repo add -n $(acrName) -g $(resourceGroupName)
    az acr helm push --name $(acrName) $(imagePath):$(Build.BuildId)
  displayName: 'Add Helm Repository to ACR'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'acr-manifest'
