trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  timeoutInMinutes: 20 # Increase timeout as needed

  steps:
  - checkout: self

  - script: |
      # Debugging step to print the artifact staging directory
      echo "Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"

      # Create the Kubernetes manifest directory if it doesn't exist
      mkdir -p $(Build.ArtifactStagingDirectory)/kubernetes-manifest

      # Remove old Kubernetes manifest files (keep the latest 5)
      Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/kubernetes-manifest -File | Sort-Object LastWriteTime -Descending | Select-Object -Skip 5 | Remove-Item -Force

      # Generate the Kubernetes manifest files with a unique identifier based on the build number
      # Dev Manifest
      cat <<EOF > $(Build.ArtifactStagingDirectory)/kubernetes-manifest/dev-manifest-$(Build.BuildNumber).yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
        namespace: dev
        labels:
          app: my-app
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
          metadata:
            labels:
              app: my-app
          spec:
            containers:
              - name: my-app
                image: personal4slim/web-image-p4s:latest # Pull from Docker Hub
                ports:
                  - containerPort: 8080
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                  - name: CONNECTION_STRING
                    value: "your_dev_database_connection_string"
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: my-app-service
        namespace: dev
      spec:
        selector:
          app: my-app
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
        type: LoadBalancer
      EOF

      # Test Manifest
      cat <<EOF > $(Build.ArtifactStagingDirectory)/kubernetes-manifest/test-manifest-$(Build.BuildNumber).yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
        namespace: test
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
          metadata:
            labels:
              app: my-app
          spec:
            containers:
              - name: my-app
                image: personal4slim/web-image-p4s:latest # Pull from Docker Hub
                ports:
                  - containerPort: 8080
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                  - name: CONNECTION_STRING
                    value: "your_test_database_connection_string"
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: my-app-service
        namespace: test
      spec:
        selector:
          app: my-app
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
        type: LoadBalancer
      EOF

      # Prod Manifest
      cat <<EOF > $(Build.ArtifactStagingDirectory)/kubernetes-manifest/prod-manifest-$(Build.BuildNumber).yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
        namespace: prod
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
          metadata:
            labels:
              app: my-app
          spec:
            containers:
              - name: my-app
                image: personal4slim/web-image-p4s:latest # Pull from Docker Hub
                ports:
                  - containerPort: 8080
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                  - name: CONNECTION_STRING
                    value: "your_prod_database_connection_string"
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: my-app-service
        namespace: prod
      spec:
        selector:
          app: my-app
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
        type: LoadBalancer
      EOF

    displayName: 'Create Kubernetes Manifests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/kubernetes-manifest'
      artifact: 'kubernetes-manifest'

  - task: Kubernetes@1
    displayName: 'Kubectl apply to Dev'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'dev-aks-p4s' # Replace with your Kubernetes service connection
      namespace: 'dev'
      command: 'apply'
      arguments: '-f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/dev-manifest-$(Build.BuildNumber).yaml'

  - task: Kubernetes@1
    displayName: 'Kubectl apply to Test'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'test-aks-p4s' # Replace with your Kubernetes service connection for test
      namespace: 'test'
      command: 'apply'
      arguments: '-f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/test-manifest-$(Build.BuildNumber).yaml'

  - task: Kubernetes@1
    displayName: 'Kubectl apply to Prod'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'prod-aks-p4s' # Replace with your Kubernetes service connection for prod
      namespace: 'prod'
      command: 'apply'
      arguments: '-f $(Build.ArtifactStagingDirectory)/kubernetes-manifest/prod-manifest-$(Build.BuildNumber).yaml'
