name: Deploy Kubernetes Cluster

trigger:
  branches:
    exclude:
      - '*'  # Replace with your branch exclusion pattern

pr:
- '*'

jobs:
- job: deploy
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: UseTerraform@0  # Use the correct version number based on the installed version
    inputs:
      terraformVersion: 'latest'  # Use the latest Terraform version

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'cluster1'  # Use your service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az account show'

  - script: terraform init
    displayName: 'Initialize Terraform'

  - script: terraform plan -out=tfplan
    displayName: 'Plan Terraform'

  - script: terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/.terraform'
      artifact: 'terraform-output'
