trigger:
- main  # Adjust the branch name as needed

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install requests
    displayName: 'Install Python dependencies'

  - script: |
      az login --service-principal --tenant $(tenantId) --username $(servicePrincipalId) --password $(servicePrincipalKey)
      az account set --subscription $(subscriptionId)
    displayName: 'Azure Login'

  - script: |
      terraform init -reconfigure
      git add .
      git commit -m "Reconfigure Terraform backend"
      git push origin main  # Use your branch name if it's not 'main'
    displayName: 'Terraform Init and Push'

  - script: |
      terraform plan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
