trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildTerraformArtifact
  displayName: 'Build Terraform Artifact'
  
  steps:
  - checkout: none  # Do not checkout the source code repository

  - script: |
      # Define the GitHub repository and folder path
      github_repo="personal4slim/p4s-deploy"
      folder_path="smalldeploy"

      # Create a GitHub Personal Access Token (PAT) with 'repo' and 'workflow' scopes and store it as a secret in Azure DevOps.

      # Fetch the contents of the folder using curl and the GitHub API
      curl -sL -H "Authorization: token $(PAT)" -o temp.zip \
        "https://api.github.com/repos/$github_repo/zipball/master/$folder_path"

      # Unzip the downloaded contents to the artifact directory
      unzip -q temp.zip -d "$(Build.ArtifactStagingDirectory)/$folder_path"

      # Clean up the temporary zip file
      rm temp.zip
    env:
      PAT: $(GitHubPAT)  # Replace with the name of the Azure DevOps secret containing your GitHub PAT
    displayName: 'Create Terraform Artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/smalldeploy'
      artifact: 'TerraformArtifact'
