name: Deploy Kubernetes Cluster

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest  # Use the latest Terraform version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_CONNECTION_CLUSTER1 }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-output
          path: .terraform
