trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildTerraformArtifact
  displayName: 'Build Terraform Artifact'
  
  steps:
  - checkout: self

  - script: |
      # Define the folder path you want to include in the artifact
      folder_path="smalldeploy"

      # Copy the contents of the folder to the artifact staging directory
      cp -R "$folder_path" "$(Build.ArtifactStagingDirectory)"
    displayName: 'Create Terraform Artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'TerraformArtifact'
