trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TerraformDeployment
  jobs:
  - job: RunTerraform
    displayName: 'Run Terraform'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: UseDotNet@2
      inputs:
        packageType: 'runtime'
        version: '3.x'

    - script: |
        az login --service-principal --username "$(servicePrincipalId)" --password "$(servicePrincipalKey)" --tenant "$(tenantId)"
        cd smalldeploy  # Navigate to the folder containing your Terraform code
        terraform init
        terraform plan
        terraform apply -auto-approve
      displayName: 'Terraform Init, Plan, and Apply'
